let bevarage = [
  "Minute Maid® Strawberry Watermelon Slushie",
  "Minute Maid® Tropical Mango Slushie",
  "Coca-Cola®",
  "Sprite®",
  "Dr Pepper®",
  "Fanta® Orange",
  "Diet Coke®",
  "Hi-C® Orange Lavaburst®",
  "Sweet Tea",
  "Unsweetened Iced Tea",
  "DASANI® Water",
  "Minute Maid® Premium Orange Juice",
  "Honest Kids® Appley Ever After® Organic Juice Drink",
  "1% Low Fat Milk Jug",
  "Reduced Sugar* Low Fat Chocolate Milk Jug",
  "Strawberry Banana Smoothie",
  "Mango Pineapple Smoothie",
  "Hot Chocolate",
  "Hot Tea",
];

let bevarageImg = [
  "https://s7d1.scene7.com/is/image/mcdonalds/Header_MediumStrawberryWatermelonSlushie_Glass_832x472:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/Header_MediumTropicalMangoSlushie_Glass_832x472:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Coca-Cola-Classic-Small-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sprite-Small:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Dr-Pepper-Small-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-fanta-orange-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Diet-Coke-Small-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-hi-c-lavaburst:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Iced-Tea-Large-drink:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Iced-Tea-Large-unsweetened:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Dasani-Water:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Minute-Maid-Orange-Juice-Medium-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-appley-ever-after:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-1-Low-Fat-Milk-Jug:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Fat-Free-Chocolate-Milk-Jug:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Strawberry-Banana-Smoothie-Medium:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Mango-Pineapple-Smoothie-Small:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McCafe-Hot-Chocolate-Medium:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-hot-tea:1-4-product-tile-desktop",
];

let breakFast = [
  "Bacon, Egg & Cheese Biscuit",
  "Egg McMuffin®",
  "Sausage McMuffin®",
  "Sausage McMuffin® with Egg",
  "Sausage Biscuit",
  "Sausage Biscuit with Egg",
  "Bacon, Egg & Cheese McGriddles®",
  "Sausage McGriddles®",
  "Sausage, Egg & Cheese McGriddles®",
  "Big Breakfast®",
  "Big Breakfast® with Hotcakes",
  "Hotcakes",
  "Hotcakes and Sausage",
  "Sausage Burrito",
  "Hash Browns",
  "Fruit & Maple Oatmeal",
];

let breakFastImg = [
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Bacon-Egg-Cheese-Biscuit-Regular-Size-Biscuit-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Egg-McMuffin-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-McMuffin:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-McMuffin-with-Egg:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-Biscuit-Regular-Size-Biscuit-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-Biscuit-with-Egg-Regular-Size-Biscuit-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Bacon-Egg-Cheese-McGriddles:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-McGriddles:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-Egg-Cheese-McGriddles-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/s-mcdonalds-Big-Breakfast-Regular-Size-Biscuit-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Big-Breakfast-with-Hotcakes-Regular-Size-Biscuit-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Hotcakes:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Hotcakes-and-Sausage:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-Burrito-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-HASH-BROWNS-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Fruit-Maple-Oatmeal-1:1-4-product-tile-desktop",
];

let burger = [
  "Big Mac®",
  "Quarter Pounder®* with Cheese",
  "Double Quarter Pounder®* with Cheese",
  "Quarter Pounder®* with Cheese Deluxe",
  "McDouble®",
  "Quarter Pounder®* with Cheese Bacon",
  "Cheeseburger",
  "Double Cheeseburger",
  "Hamburger",
];
let burgerImg = [
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Big-Mac-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Quarter-Pounder-with-Cheese-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Double-Quarter-Pounder-with-Cheese-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-qpc-deluxe-burger:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McDouble-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-qpc-bacon-burger:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Cheeseburger-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Double-Cheeseburger-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Hamburger:1-4-product-tile-desktop",
];
let ChickenSandwich = [
  "Big Mac®",
  "Quarter Pounder®* with Cheese",
  "Double Quarter Pounder®* with Cheese",
  "Quarter Pounder®* with Cheese Deluxe",
  "McDouble®",
  "Quarter Pounder®* with Cheese Bacon",
  "Cheeseburger",
];
let ChickenSandwichImg = [
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-spicy-deluxe-crispy-chicken-sandwich:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-crispy-chicken-sandwich:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-spicy-crispy-chicken-sandwich:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-deluxe-crispy-chicken-sandwich:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Chicken-McNuggets-4pc-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McChicken-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Filet-O-Fish-1:1-4-product-tile-desktop",
];

let comboMeal = [
  "Big Mac® Combo Meal",
  "Cheeseburger Combo Meal",
  "Quarter Pounder®* with Cheese Meal",
  "Double Quarter Pounder®* with Cheese Meal",
  "Crispy Chicken Sandwich Combo Meal",
  "Spicy Crispy Chicken Sandwich Combo Meal",
  "Deluxe Crispy Chicken Sandwich Combo Meal",
  "10 piece Chicken McNuggets® Meal",
  "Filet-O-Fish® Meal",
  "Egg McMuffin® Meal",
  "Sausage McMuffin® with Egg Meal",
  "Sausage Biscuit with Egg Meal",
  "Bacon, Egg & Cheese Biscuit Meal",
  "Bacon, Egg & Cheese McGriddles® Meal",
  "Sausage, Egg & Cheese McGriddles® Meal",
  "Sausage McGriddles® Meal",
  "Sausage Burrito Meal",
];
let comboMealImg = [
  "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Big-Mac-Extra-Value-Meals:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-2-Cheeseburger-Extra-Value-Meals:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Quarter-Pounder-with-Cheese-Extra-Value-Meals:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Double-Quarter-Pounder-with-Cheese-Extra-Value-Meals-combo:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/h-crispy-chicken-sandwich-meal:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/h-spicy-crispy-chicken-sandwich-meal-combo:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/h-deluxe-crispy-chicken-sandwich-meal:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Chicken-McNuggets-10-piece-Extra-Value-Meals:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Filet-O-Fish-Extra-Value-Meals:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Egg-McMuffin-Extra-Value-Meals:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Sausage-McMuffin-with-Egg-Extra-Value-Meals:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Sausage-Biscuit-with-Egg-Extra-Value-Meals:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Bacon-Egg-Cheese-Biscuit-Extra-Value-Meals:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Bacon-Egg-Cheese-McGriddles-Extra-Value-Meals:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Sausage-Egg-Cheese-McGriddles-Extra-Value-Meals:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Sausage-McGriddles-Extra-Value-Meals:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Sausage-Burrito-2-Extra-Value-Meals:1-4-product-tile-desktop",
];

let desert = [
  "Chocolatey Pretzel McFlurry®",
  "McFlurry® with OREO® cookies",
  "McFlurry® with M&M'S® Candies",
  "Vanilla Cone",
  "Chocolate Shake",
  "Vanilla Shake",
  "Strawberry Shake",
  "Hot Fudge Sundae",
  "Hot Caramel Sundae",
  "Baked Apple Pie",
  "Chocolate Chip Cookie",
];

let desertImg = [
  "https://s7d1.scene7.com/is/image/mcdonalds/Header_ChocolatePretzelMcFlurry_v8_832x472:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-oreo-mcflurry-snack:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mm-mcflurry-snack:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Vanilla-Reduced-Fat-Ice-Cream-Cone:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Chocolate-McCafe-Shake-Medium-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Vanilla-McCafe-Shake-Medium-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Strawberry-McCafe-Shake-Medium-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Hot-Fudge-Sundae:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Hot-Caramel-Sundae-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Baked-Hot-Apple-Pie-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Chocolate-Chip-Cookie-mcd:1-4-product-tile-desktop",
];

let happyMeal = [
  "Hamburger Happy Meal®",
  "4 Piece Chicken McNuggets® Happy Meal",
  "6 Piece Chicken McNuggets® Happy Meal",
];

let happyMealImg = [
  "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Hamburger:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/h-mcdonalds-Chicken-McNuggets:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-Chicken-McNuggets-Mighty-Kids-Meals:1-4-product-tile-desktop",
];

let drinks = [
  "Caramel Macchiato",
  "Iced Caramel Macchiato",
  "Cappuccino",
  "Caramel Cappuccino",
  "French Vanilla Cappuccino",
  "Mocha",
  "Iced Mocha",
  "Latte",
  "Iced Latte",
  "Caramel Latte",
  "Iced Caramel Latte",
  "French Vanilla Latte",
  "Iced French Vanilla Latte",
  "Americano",
  "Premium Roast Coffee",
  "Iced Coffee",
  "Iced Caramel Coffee",
  "Iced French Vanilla Coffee",
  "Caramel Frappé",
  "Mocha Frappé",
  "Hot Chocolate",
  "Strawberry Banana Smoothie",
  "Mango Pineapple Smoothie",
];

let drinksImg = [
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-caramel-macchiato:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-iced-caramel-macchiato-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-cappuccino-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-caramel-cappuccino:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-vanilla-cappuccino:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McCafe-Mocha-Medium:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McCafe-Iced-Mocha-Medium-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McCafe-Latte-Medium:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-iced-latte-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McCafe-Caramel-Latte-Medium:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-iced-caramel-latte:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McCafe-Vanilla-Latte-Medium:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-iced-french-vanilla-latte-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-americano-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Coffee-Medium:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Premium-Roast-Iced-Coffee-Medium:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Caramel-Iced-Coffee:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Vanilla-Iced-Coffee:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Frappe-Caramel-Medium-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Frappe-Mocha-Medium:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McCafe-Hot-Chocolate-Medium:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Strawberry-Banana-Smoothie-Medium:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Mango-Pineapple-Smoothie-Small:1-4-product-tile-desktop",
];

let bakery = ["Apple Fritter", "Blueberry Muffin", "Cinnamon Roll"];
let bakeryImg = [
  "https://s7d1.scene7.com/is/image/mcdonalds/t-apple-fritter-bakery:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-blueberry-muffin-bakery-mcd:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-cinnamon-roll-mcbakery:1-4-product-tile-desktop",
];

let fries = ["World Famous Fries®", "Apple Slices"];
let friesImg = [
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-fries-small:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Apple-Slices:1-4-product-tile-desktop",
];

let dollerMenu = [
  "Sausage Biscuit",
  "Sausage McMuffin®",
  "Sausage McGriddles®",
  "Hash Browns",
  "Mocha",
  "Caramel Mocha",
  "Latte",
  "Caramel Latte",
  "French Vanilla Latte",
  "Caramel Macchiato",
  "Caramel Frappé",
  "Mocha Frappé",
  "Strawberry Banana Smoothie",
  "Mango Pineapple Smoothie",
  "McDouble®",
  "McChicken®",
  "Chicken McNuggets®",
  "World Famous Fries®",
  "Coca-Cola®",
  "Sprite®",
  "Fanta® Orange",
  "Dr Pepper®",
  "Diet Coke®",
  "Hi-C® Orange Lavaburst®",
  "Unsweetened Iced Tea",
  "Sweet Tea",
];
let dollerMenuImg = [
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-Biscuit-Regular-Size-Biscuit-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-McMuffin:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sausage-McGriddles:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-HASH-BROWNS-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McCafe-Mocha-Medium:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McCafe-Caramel-Mocha-Medium:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McCafe-Latte-Medium:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McCafe-Caramel-Latte-Medium:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McCafe-Vanilla-Latte-Medium:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-caramel-macchiato:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Frappe-Caramel-Medium-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Frappe-Mocha-Medium:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Strawberry-Banana-Smoothie-Medium:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Mango-Pineapple-Smoothie-Small:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McDouble-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-McChicken-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Chicken-McNuggets-4pc-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-fries-small:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Coca-Cola-Classic-Small-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Sprite-Small:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-fanta-orange-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Dr-Pepper-Small-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Diet-Coke-Small-1:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-hi-c-lavaburst:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Iced-Tea-Large-unsweetened:1-4-product-tile-desktop",
  "https://s7d1.scene7.com/is/image/mcdonalds/t-mcdonalds-Iced-Tea-Large-drink:1-4-product-tile-desktop",
];
